spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
      access-key: LTAI5tHJFdMmWtTmb9X614sP
      secret-key: MmKpvd4fxPAPK7xWYpiAqXNKrYKKr5
  application:
    name: cubemall-third-party
server:
  port: 30000